<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class RouteExpense extends Model
{
    use HasFactory;

    protected $fillable = [
        'tenant_id',
        'route_id',
        'shipment_id',
        'cost_type',
        'description',
        'amount',
        'allocation_method',
        'operator_type',
        'third_party_name',
        'third_party_cte_xml_id',
        'leg',
        'notes',
        'receipt_url',
        'created_by',
    ];

    protected $casts = [
        'amount' => 'decimal:2',
        'tenant_id' => 'integer',
        'route_id' => 'integer',
        'shipment_id' => 'integer',
        'third_party_cte_xml_id' => 'integer',
        'created_by' => 'integer',
    ];

    /**
     * Get the tenant that owns the route expense.
     */
    public function tenant(): BelongsTo
    {
        return $this->belongsTo(Tenant::class);
    }

    /**
     * Get the route that owns the expense.
     */
    public function route(): BelongsTo
    {
        return $this->belongsTo(Route::class);
    }

    /**
     * Get the shipment/CT-e if this expense is directly linked.
     */
    public function shipment(): BelongsTo
    {
        return $this->belongsTo(Shipment::class);
    }

    /**
     * Get the third party CT-e XML linked to this expense if applicable.
     */
    public function thirdPartyCteXml(): BelongsTo
    {
        return $this->belongsTo(CteXml::class, 'third_party_cte_xml_id');
    }

    /**
     * Get the creator of this expense.
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Get all cost allocations generated by this route expense.
     */
    public function allocations(): HasMany
    {
        return $this->hasMany(ShipmentCostAllocation::class);
    }
}
